#server.port=9090
#spring.datasource.url=jdbc:mysql://localhost:3306/userdatabase
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

server:
 port: 9000
 
spring:
 datasource:
  username: root
  password: root
  url: jdbc:mysql://localhost:3306/userdatabase
 jpa:
   show-sql: true
 hibernate:
   ddl-auto: update
 
   
  
  
